language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - PIP_USE_MIRRORS=true

install:
  - python setup.py install
  - pip install coveralls

script:
  - python setup.py test
  - coverage run --source=goliath setup.py test

after_success:
- coveralls